# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsdb', '0002_wtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtime',
            name='online',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
