# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsdb', '0003_wtime_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='document_link2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='document_link3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='language',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='media_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
