# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songsdb', '0004_auto_20170728_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=200)),
                ('copyright_text', models.CharField(max_length=500)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songsdb.Publisher')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='songsdb.Collection'),
        ),
    ]
