# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-16 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsdb', '0006_song_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_num',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
